### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by Aoiwhite** [poooi/plugin-navy-album#3]
![QQ图片20200717224439](https://user-images.githubusercontent.com/33090165/87799208-8a01d880-c87f-11ea-96e3-cd15bf4f03ed.png)
不管我怎么拉长，就是看不到底，还不能缩放。这问题好几年了，能解决一下吗

**Comment by Javran** [comment]
滚动功能确实一直有点奇怪的问题,一直打算重新搞一遍顺便迁移blueprint.
提高点优先级好了.

**Comment by Javran** [comment]
1.3.3已发布,这个问题应该是修了,还有问题再开.

**Comment by Aoiwhite** [comment]
感谢，很棒了。
![image](https://user-images.githubusercontent.com/33090165/89355983-47e5ed00-d6ef-11ea-9e48-c1052746b3ca.png)
边缘的鼠标悬停显示不全，要是能再解决掉这点小瑕疵就完美了
